name: Hola Mundo + SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          # Sonar recomienda desactivar shallow clone para tener mejor contexto
          fetch-depth: 0

      - name: Hola Mundo
        run: echo "Hola Mundo desde GitHub Actions con SonarCloud!"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Si quieres pasar parámetros extra (opcional),
        # puedes usar args, pero para el hola mundo basta
        # con sonar-project.properties
        # with:
        #   args: >
        #     "-Dsonar.organization=TU_ORGANIZATION_KEY"
        #     "-Dsonar.projectKey=TU_PROJECT_KEY"
        #     "-Dsonar.sources=."
