name: Hola Mundo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hola_mundo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Imprimir Hola Mundo
        run: echo "Hola Mundo desde GitHub Actions!"
